Add daemon mode continue (WIP)
magnusbaeck/logstash-filter-verifier pull request #106
Opened 2021-04-02 19:46 UTC by breml

@magnusbaeck I continued to work on the daemon mode. There are still quite some issues to be resolved and features to be added. Feel free to have a look. If you do review this, give me a shout, such that I can continue on a different branch with the further development.

The most interesting features, that have been added are:

* Support for codecs in input plugin
* Support multiple inputs
* Make the @metadata key configurable

Additionally some bug fixing and small improvements here and there.

I also updated the checklist in https://github.com/magnusbaeck/logstash-filter-verifier/issues/96#issuecomment-797559730

2021-04-04 17:44 UTC, magnusbaeck commented
Starting to look at this now. Should I go ahead and push commits that look fine into master as I go along? Will obviously only work until I have comments for a commit, but still.

2021-04-04 17:47 UTC, breml commented
As you like. I forked a new branch for my current work. If you have comments, I will decide if I fix them on the PR or on my new branch depending on complexity and effort. When ever this PR is merged, I will rebase my new branch on master before creating a new PR.

2021-04-05 20:06 UTC, magnusbaeck requested changes
Review done with just a couple of comments.

I pushed the first handful of commits to decrease the PR size and potential future rebase work.

2021-04-06 19:33 UTC, breml commented on internal/daemon/logstashconfig/file.go
>  	// can be referenced in the test case configuration.
You are right, this is implemented now.

2021-04-06 19:35 UTC, breml commented on internal/testcase/testcase.go
> +	InputPlugin string `json:"input_plugin" yaml:"input_plugin"`
Fixed, changed to snake case.

2021-04-06 19:40 UTC, breml commented
@magnusbaeck I addressed your review feedback and updated the PR.

2021-04-07 18:45 UTC, magnusbaeck approved these changes

2021-04-07 18:46 UTC, merged